# https://docs.github.com/ja/actions/creating-actions/creating-a-javascript-action#creating-an-action-metadata-file
name: 'show commits'
description: 'blah blah blah'
inputs:
  GITHUB_TOKEN:
    description: 'GITHUB_TOKEN'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
