name: macOS installation
on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          brew tap kitsuyui/playground
          brew update
          brew install mymyip
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_NO_ANALYTICS: 1
