name: macOS installation
on:
  push:
    branches:
      - '*'
  schedule:
    # UTC 04:45 は JST 13:45
    - cron: '45 4 * * *'

jobs:
  test_installation:
    strategy:
      matrix:
        macos: [macos-11, macos-12]
    runs-on: ${{ matrix.macos }}
    steps:
      - uses: actions/checkout@v3

      - run: |
          # URL を指定しないと https://github.com/kitsuyui/homebrew-playground を見に行くらしい
          brew tap kitsuyui/playground https://github.com/kitsuyui/playground

      - run: |
          cd /usr/local/Homebrew/Library/Taps/kitsuyui/homebrew-playground/
          git checkout ${{ github.ref_name }}  # このブランチをテストしたい
        if: ${{ github.ref_name != 'main' }}

      - run: |
          uname -m
          brew install mymyip
          mymyip --help

        env:
          HOMEBREW_NO_AUTO_UPDATE: '1'
          HOMEBREW_NO_INSTALL_CLEANUP: '1'
          HOMEBREW_NO_ENV_HINTS: '1'
